[project]
name = "goobits-cli"
version = "1.2.0"
description = "Unified CLI for Goobits projects."
dependencies = [ "pyyaml", "jinja2", "pydantic", "typer", "toml", "rich-click",]

[build-system]
requires = [ "setuptools>=61.0", "wheel",]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [ "pytest", "pytest-cov",]
dev = [ "mypy", "types-PyYAML", "types-toml", "ruff",]

[project.scripts]
goobits = "goobits_cli.generated_cli:cli_entry"

[tool.pytest.ini_options]
pythonpath = [ "src",]
testpaths = [ "src/tests",]
